{
 "title": "Couchbase_test",
 "description": "Couchbase 5+ dashboard, created for totvslabs/couchbase-exporter",
 "tags": [ "couchbase" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(couchbase_bucket_basicstats_dataused_bytes, instance)"
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "label_values(couchbase_bucket_basicstats_dataused_bytes{instance=\"$instance\"}, bucket)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Balanced",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "couchbase_cluster_balanced{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rebalance Progress",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "couchbase_task_rebalance_progress{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Compacting Progress",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(couchbase_task_compacting_progress{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Bucket RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 * (sum by (bucket) (couchbase_bucket_basicstats_memused_bytes{bucket=~\"$bucket\",instance=~\"$instance\"})) / sum by (bucket) (couchbase_bucket_stats_ep_max_size_bytes{bucket=~\"$bucket\",instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Server Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(couchbase_node_healthy{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Server Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(couchbase_node_healthy{instance=~\"$instance\"} == 0) or (1-absent(couchbase_node_healthy{instance=~\"$instance\"} == 0))"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (couchbase_bucket_stats_cmd_set{bucket=~\"$bucket\",instance=~\"$instance\"}) + sum by (bucket) (couchbase_bucket_stats_cmd_get{bucket=~\"$bucket\",instance=~\"$instance\"})",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_ep_cache_miss_rate{bucket=~\"$bucket\",instance=~\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_curr_connections{bucket=~\"$bucket\",instance=~\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Primary items total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_curr_items{bucket=~\"$bucket\",instance=~\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Gets / Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_cmd_set{bucket=~\"$bucket\",instance=~\"$instance\"}",
     "legendFormat": "Sets on {{ bucket }}"
    },
    {
     "expr": "couchbase_bucket_stats_cmd_get{bucket=~\"$bucket\",instance=~\"$instance\"}",
     "legendFormat": "Gets on {{ bucket }}"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_evictions{bucket=~\"$bucket\",instance=~\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Resident Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "couchbase_bucket_stats_vbuckets_active_resident_items_ratio{bucket=~\"$bucket\",instance=~\"$instance\"}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * couchbase_bucket_basicstats_memused_bytes{bucket=~\"$bucket\",instance=~\"$instance\"} / couchbase_bucket_stats_ep_max_size_bytes",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Items Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_curr_items{bucket=~\"$bucket\",instance=~\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Hard Out of Memory Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(couchbase_bucket_stats_ep_oom_errors{instance=\"$instance\", bucket=~\"$bucket\"}[5m])",
       "legendFormat": "{{ bucket }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Fetches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_basicstats_diskfetches{instance=~\"$instance\", bucket=~\"$bucket\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Disk Write Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_disk_write_queue{instance=~\"$instance\", bucket=~\"$bucket\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compacting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fragmentation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_couch_docs_fragmentation{instance=~\"$instance\", bucket=~\"$bucket\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Compaction Progress",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "couchbase_task_compacting_progress{instance=~\"$instance\", bucket=~\"$bucket\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rebalance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rebalance Progress",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "couchbase_task_rebalance_progress{instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "DCP Replication",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_producers{instance=~\"$instance\", bucket=~\"$bucket\"}",
       "legendFormat": "{{ bucket }}: DCP Senders"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replicas{instance=~\"$instance\", bucket=~\"$bucket\"}",
       "legendFormat": "{{ bucket }}: DCP Connections"
      }
     ]
    },
    {
     "title": "Items Sent / Remaining",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_items_sent{instance=~\"$instance\", bucket=~\"$bucket\"}",
       "legendFormat": "Sent on {{ bucket }}"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_items_remaining{instance=~\"$instance\", bucket=~\"$bucket\"}",
       "legendFormat": "Remaining on {{ bucket }}"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_replica_total_bytes{instance=~\"$instance\", bucket=~\"$bucket\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    }
   ]
  },
  {
   "title": "XDCR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Items Sent / Remaining",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_items_remaining{bucket=~\"$bucket\",instance=~\"$instance\"}",
       "legendFormat": "{{ bucket }}: Remaining"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_items_sent{bucket=~\"$bucket\", instance=~\"$instance\"}",
       "legendFormat": "{{ bucket }}: Sent"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_total_bytes{bucket=~\"$bucket\", instance=~\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "Backlog Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_total_backlog_size{bucket=~\"$bucket\", instance=~\"$instance\"}",
       "legendFormat": "{{ bucket }}"
      }
     ]
    },
    {
     "title": "DCP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_connections{bucket=~\"$bucket\", instance=~\"$instance\"}",
       "legendFormat": "{{ bucket }}: connections"
      },
      {
       "expr": "couchbase_bucket_stats_ep_dcp_xdcr_producers{bucket=~\"$bucket\", instance=~\"$instance\"}",
       "legendFormat": "{{ bucket }}: producers"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "couchbase_cluster_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "cluster"
      },
      {
       "expr": "couchbase_bucket_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "bucket"
      },
      {
       "expr": "couchbase_node_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "node"
      },
      {
       "expr": "couchbase_task_scrape_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "task"
      }
     ]
    }
   ]
  }
 ]
}